export default {
  backHome: '← Back to home',
  updatedLabel: 'Effective date: 5 August 2026',
  legal: {
    title: 'Legal Notice',
    metaDesc: 'ZEROVECTOR LIMITED legal notice: site ownership, nature of content, scope of professional services, intellectual property and limitation of liability.',
    sections: [
      { h: 'Site Ownership', ps: ['This website (zerovector.hk) is owned and operated by ZEROVECTOR LIMITED (the "Company"), a limited company incorporated in the Hong Kong SAR, focused on RegTech services including blockchain analytics, asset security and digital forensics. Contact: support@zerovector.hk.'] },
      { h: 'Nature of Content', ps: ['Content on this website is provided for general information only. It does not constitute legal, financial, investment or other professional advice, nor an offer or commitment of any kind. The scope, terms and conditions of any engagement are governed exclusively by a signed engagement agreement.'] },
      { h: 'Scope of Professional Services', ps: ['The Company is a technology services firm, not a law firm, and does not provide legal opinions or legal services of any kind. Where your matter requires legal advice, you should engage licensed lawyers or law firms directly; upon engagement, the Company can provide technical analysis and evidentiary materials for their reference. Our analytical reports and technical support do not constitute, and are no substitute for, legal advice.'] },
      { h: 'Virtual Asset Compliance', ps: ['The Company does not operate a virtual-asset trading platform and does not provide fiat-to-VA or VA-to-VA exchange, trade matching, token issuance financing, derivatives trading, custody or investment advice. Such activities require licensing in the Hong Kong SAR and are prohibited financial activities in Mainland China.', 'Our services are technical in nature — analytics, security and forensics. We do not buy, sell or recommend any virtual asset on behalf of clients. Virtual assets are highly volatile; nothing on this website constitutes investment advice or solicitation.', 'Users are responsible for ensuring that their use of our services and products complies with the laws of their own jurisdiction, including Mainland China regulations concerning virtual currency.'] },
      { h: 'Use of Findings and Reports', ps: ['Analytical findings and forensic reports issued by the Company are limited to the purpose and scope set out in the relevant engagement agreement. Without the Company’s written consent, no person may use a report beyond its agreed purpose or represent the Company as endorsing their conclusions.'] },
      { h: 'Intellectual Property', ps: ['All text, graphics, marks (including the ZEROVECTOR logo), product names (Sealr, MerkleClaw, ThreatLedger) and page designs on this website belong to the Company or its affiliates and are protected by applicable intellectual property laws. They may not be copied, modified, distributed or used commercially without written authorization.'] },
      { h: 'Third-party Websites', ps: ['This website contains links to third-party websites (including the product sites sealr.io, merkleclaw.com and threatledger.net). Those sites are the responsibility of their respective operators, and this notice does not apply to them.'] },
      { h: 'Limitation of Liability', ps: ['To the maximum extent permitted by applicable law, the Company accepts no liability for any direct or indirect loss arising from the use of, or inability to use, this website, including decisions made in reliance on its content.'] },
      { h: 'Governing Law', ps: ['This notice is governed by and construed in accordance with the laws of the Hong Kong SAR.'] },
    ],
  },
  privacy: {
    title: 'Privacy Policy',
    metaDesc: 'ZEROVECTOR LIMITED privacy policy: no tracking cookies on this site; how personal data is collected, used and shared, and your rights under the PDPO.',
    sections: [
      { h: 'Introduction', ps: ['This policy explains how ZEROVECTOR LIMITED handles personal data when you use this website or contact us. The Company complies with the Hong Kong Personal Data (Privacy) Ordinance (Cap. 486) and other applicable data protection requirements.'] },
      { h: 'Data Collected on This Site', ps: ['This website sets no tracking cookies and uses no third-party advertising or behavioral analytics.', 'When you contact us by email or other means, we collect the name, contact details, organization and inquiry content you choose to provide.'] },
      { h: 'Technical Logs', ps: ['This website is hosted on third-party infrastructure whose providers may record technical logs (such as IP address and access time) for security and operations, subject to their own policies.'] },
      { h: 'How We Use Data', ps: ['We use personal data only to respond to inquiries and assess engagement needs; to perform signed service agreements; to comply with legal and regulatory requirements; and to keep our services secure.'] },
      { h: 'Data in Engagements', ps: ['Data accessed in the course of an engagement, including materials provided by clients, is handled under the engagement agreement and confidentiality arrangements. Our analysis of public blockchain data is not aimed at identifying members of the general public.'] },
      { h: 'Sharing', ps: ['We do not sell personal data. We share it only with your consent, where necessary to perform an engagement (for example with external professional advisers you have approved), or where required by law or competent authorities.'] },
      { h: 'Retention and Security', ps: ['Personal data is kept only as long as needed for the purposes described in this policy, protected by encryption, access controls and other measures proportionate to risk.'] },
      { h: 'Your Rights', ps: ['Under the PDPO you may request access to, and correction of, personal data we hold about you. Contact support@zerovector.hk.'] },
      { h: 'Product Privacy Policies', ps: ['Sealr, MerkleClaw and ThreatLedger maintain their own privacy policies on their respective platforms.'] },
      { h: 'Updates', ps: ['This policy may be updated from time to time; updates are published on this page with a revised effective date.'] },
    ],
  },
  terms: {
    title: 'Terms of Service',
    metaDesc: 'ZEROVECTOR LIMITED website terms of service: permitted use, no professional advice, intellectual property, limitation of liability and governing law.',
    sections: [
      { h: 'Acceptance', ps: ['By accessing or using this website you agree to be bound by these terms. If you do not agree, please discontinue use.'] },
      { h: 'Purpose of the Site', ps: ['This website presents the Company, its services and products. Information on the site does not constitute an offer; any engagement, its scope, fees and deliverables are governed exclusively by a separately signed engagement or service agreement.'] },
      { h: 'No Professional Advice', ps: ['Website content does not constitute legal, financial, investment or other professional advice. The Company does not provide legal services; you should seek independent advice from licensed professionals on specific matters.'] },
      { h: 'Acceptable Use', ps: ['You agree to use this website lawfully and not to: interfere with or disrupt its operation; scrape, copy or commercially exploit its content without authorization; impersonate the Company or its personnel; or use it for any unlawful activity.'] },
      { h: 'Local Compliance', ps: ['You are responsible for ensuring that your use of this website and of the Company’s services and products is lawful in your jurisdiction. The Company does not solicit business in any jurisdiction where such activities are prohibited; users in Mainland China in particular must comply with applicable virtual-currency regulations.'] },
      { h: 'Intellectual Property', ps: ['Intellectual property in the website content belongs to the Company or its affiliates and may not be used without written consent, except as permitted by law.'] },
      { h: 'Third-party Products and Links', ps: ['Use of the products (Sealr, MerkleClaw, ThreatLedger) is governed by their own terms and policies. Links to third-party sites do not imply endorsement.'] },
      { h: 'Disclaimer and Limitation of Liability', ps: ['This website is provided "as is". To the maximum extent permitted by applicable law, the Company does not warrant uninterrupted or error-free operation and is not liable for indirect, incidental or consequential losses arising from use of the site.'] },
      { h: 'Changes', ps: ['The Company may revise these terms from time to time; revisions take effect upon publication on this page.'] },
      { h: 'Governing Law and Jurisdiction', ps: ['These terms are governed by the laws of the Hong Kong SAR. Disputes should first be resolved through consultation; failing that, they are subject to the jurisdiction of the Hong Kong SAR courts.'] },
    ],
  },
};
